const CHARACTER_PROMPTS = {
  luna: { name: 'Luna', emoji: '🐱', colors: { body: '#F8A0B8', accent: '#9B6FD4', outfit: '#5EC8C8' }, base: `Luna, a cute pink cat character for children's animation, solid pink body color, big round black eyes with long eyelashes, small pink cat ears, rosy cheek blush marks, thin black whiskers, purple bow on head, teal dress with yellow heart, 2D flat cartoon illustration, clean smooth outlines, solid flat colors NO gradients NO shadows, chibi proportions big head small body, white solid background, Tunki Tunes children animated series style ages 3-7` },
  dino: { name: 'Dino', emoji: '🦖', colors: { body: '#7BC67E', belly: '#D4ED91', accessory: '#FF6B35' }, base: `Dino, a cute baby dinosaur character for children's animation, solid green body, lighter yellow-green belly, darker green spikes on back and head, big round black eyes, expressive dark eyebrows, small green freckles, orange-red bandana accessory, wide happy open mouth, chubby round body, 2D flat cartoon illustration, clean smooth outlines, solid flat colors NO gradients NO shadows, chibi proportions big head small body, white solid background, Tunki Tunes children animated series style ages 3-7` },
  pipo: { name: 'Pipo', emoji: '🐥', colors: { body: '#FFD93D', beak: '#FF8C42', outfit: '#5B9BD5' }, base: `Pipo, a cute baby chick character for children's animation, solid yellow round body, small orange beak, big round black eyes, tiny orange feet, very round and chubby shape, blue hoodie with musical note detail, super round head, 2D flat cartoon illustration, clean smooth outlines, solid flat colors NO gradients NO shadows, chibi proportions very round big head, white solid background, Tunki Tunes children animated series style ages 3-7` },
  nubi: { name: 'Nubi', emoji: '🐶', colors: { body: '#9B7FD4', outfit: '#5EC8C8' }, base: `Nubi, a cute puppy dog character for children's animation, solid purple lavender body, big floppy droopy ears in darker purple, big round black eyes, small black nose, rosy cheek blush marks, wide friendly smile, teal t-shirt with white cloud graphic, chubby round body, 2D flat cartoon illustration, clean smooth outlines, solid flat colors NO gradients NO shadows, chibi proportions big head small body, white solid background, Tunki Tunes children animated series style ages 3-7` },
  miel: { name: 'Miel', emoji: '🐝', colors: { body: '#FFD700', stripes: '#2D2D2D' }, base: `Miel, a cute bee character for children's animation, yellow and black striped body, round black glasses on face, small antennae on head, big round black eyes behind glasses, small transparent wings, happy smiling expression, chubby round bee body, tiny arms and legs, 2D flat cartoon illustration, clean smooth outlines, solid flat colors NO gradients NO shadows, chibi proportions big head small round body, white solid background, Tunki Tunes children animated series style ages 3-7` },
  estrellita: { name: 'Estrellita', emoji: '⭐', colors: { body: '#FFD700' }, base: `Estrellita, a cute star character for children's animation, golden yellow star shape body, big round black eyes, rosy cheek blush marks, small happy smile, tiny arms and legs from star points, gentle friendly expression, 2D flat cartoon illustration, clean smooth outlines, solid flat colors NO gradients NO shadows, white solid background, Tunki Tunes children animated series style ages 3-7` }
};

const SCENARIO_PROMPTS = {
  bosque_tunki: `Tunki Forest background, simple flat 2D illustration, soft green trees round shapes, light blue sky solid color, green grass solid color, simple round colorful flowers, NO gradients NO shadows, flat solid colors`,
  casa_club: `Tunki Club House interior, simple flat 2D illustration, warm cream walls solid color, cozy interior, big colorful cushions, simple window with curtains, wooden floor flat color, NO gradients NO shadows, flat solid colors`,
  pradera_musical: `Tunki Musical Meadow background, simple flat 2D illustration, bright yellow-green grass solid color, light blue sky solid color, simple round hills, colorful musical notes floating, NO gradients NO shadows, flat solid colors`,
  cueva_suenos: `Tunki Dream Cave background, simple flat 2D illustration, soft purple cave walls solid color, simple crystal shapes, dark blue background with simple star shapes, NO gradients NO shadows, flat solid colors`,
  rio_brillante: `Tunki Bright River background, simple flat 2D illustration, turquoise water solid color, green riverbanks, simple round stones, light blue sky solid color, NO gradients NO shadows, flat solid colors`
};

const GLOBAL_STYLE = `2D flat cartoon illustration, clean black outlines, solid flat colors ONLY, NO gradients, NO shadows, NO shading, NO texture, children animation style, Tunki Tunes series, ages 3-7, high quality illustration`;

module.exports = { CHARACTER_PROMPTS, SCENARIO_PROMPTS, GLOBAL_STYLE };
